# Generated by Django 4.1.1 on 2022-10-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automodels',
            options={'verbose_name': 'Modelis', 'verbose_name_plural': 'Modeliai'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Mašina', 'verbose_name_plural': 'Mašinos'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
    ]
