# Generated by Django 4.1.1 on 2022-10-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_automodels_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderline',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Administruojama'), ('t', 'Taisoma'), ('b', 'Baigta taisyti'), ('g', 'Galima pasiimti')], default='a', help_text='Statusas', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Bus sutaisyta'),
        ),
    ]
