# Generated by Django 4.1.1 on 2022-10-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_oderline_status_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderline',
            name='price',
            field=models.IntegerField(verbose_name='Kaina'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(verbose_name='Kaina'),
        ),
    ]
